apiVersion: networking.gke.io/v1
kind: HealthCheckPolicy
metadata:
  name: blueprints-api
  namespace: blueprints
spec:
  default:
    checkIntervalSec: 15
    timeoutSec: 15
    healthyThreshold: 3
    unhealthyThreshold: 2
    logConfig:
      enabled: true
    config:
      type: HTTP
      httpHealthCheck:
        portSpecification: 
        port: 8080
        requestPath: /healthz
  targetRef:
    group: ""
    kind: Service
    name: blueprints-api