apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: blueprints-api
  namespace: blueprints
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: blueprints-api 
  minReplicas: 1
  maxReplicas: 3
  metrics:
  - type: Object
    object:
      describedObject:
        kind: Service
        name: blueprints-api
      metric:
        name: "autoscaling.googleapis.com|gclb-capacity-utilization"
      target:
        averageValue: 70
        type: AverageValue