apiVersion: v1
kind: Service
metadata:
  name: blueprints-api
  namespace: blueprints
  labels:
    app: blueprints-api
  annotations:
    networking.gke.io/max-rate-per-endpoint: "10"
spec:
  type: ClusterIP
  selector:
    app: blueprints-api
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      name: http
