FROM golang:1.20 as build

WORKDIR /go/src/app
COPY . .

RUN go mod download
RUN go vet -v
RUN go test -v

RUN CGO_ENABLED=0 go build -o /go/bin/worker

FROM gcr.io/distroless/static-debian11

COPY --from=build /go/bin/worker /
CMD ["/worker"]