apiVersion: iam.cnrm.cloud.google.com/v1beta1
kind: IAMServiceAccount
metadata:
  name: blueprints-worker-sa
  namespace: blueprints
  annotations:
      cnrm.cloud.google.com/project-id: PROJECT_ID_VALUE
spec:
  displayName: Service account for Blueprints worker.
---
apiVersion: iam.cnrm.cloud.google.com/v1beta1
kind: IAMPolicyMember
metadata:
  name: blueprints-worker-policy-member-binding
  namespace: blueprints
spec:
  member: serviceAccount:blueprints-worker-sa@PROJECT_ID_VALUE.iam.gserviceaccount.com
  role: roles/pubsub.subscriber
  resourceRef:
    apiVersion: resourcemanager.cnrm.cloud.google.com/v1beta1
    kind: Project
    external: projects/PROJECT_ID_VALUE
---
apiVersion: iam.cnrm.cloud.google.com/v1beta1
kind: IAMPolicyMember
metadata:
  name: blueprints-worker-policy-member-binding-2
  namespace: blueprints
spec:
  member: serviceAccount:blueprints-worker-sa@PROJECT_ID_VALUE.iam.gserviceaccount.com
  role: roles/pubsub.viewer
  resourceRef:
    apiVersion: resourcemanager.cnrm.cloud.google.com/v1beta1
    kind: Project
    external: projects/PROJECT_ID_VALUE
---
apiVersion: iam.cnrm.cloud.google.com/v1beta1
kind: IAMPolicy
metadata:
  name: blueprints-worker-iampolicy-workload-identity
  namespace: blueprints
spec:
  resourceRef:
    apiVersion: iam.cnrm.cloud.google.com/v1beta1
    kind: IAMServiceAccount
    name: blueprints-worker-sa
  bindings:
    - role: roles/iam.workloadIdentityUser
      members:
        - serviceAccount:PROJECT_ID_VALUE.svc.id.goog[blueprints/blueprints-worker]