apiVersion: v1
kind: ServiceAccount
metadata:
  name: otel-collector-sa
  namespace: blueprints
  labels:
    app.kubernetes.io/component: opentelemetry-collector
    app.kubernetes.io/instance: blueprints.otel
    app.kubernetes.io/managed-by: manually
    app.kubernetes.io/name: otel-collector
    app.kubernetes.io/part-of: opentelemetry
  annotations:
    iam.gke.io/gcp-service-account: otel-collector-sa@PROJECT_ID_VALUE.iam.gserviceaccount.com
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: otel-collector-sa
  labels:
    app.kubernetes.io/component: opentelemetry-collector
    app.kubernetes.io/instance: blueprints.otel
    app.kubernetes.io/managed-by: manually
    app.kubernetes.io/name: otel-collector
    app.kubernetes.io/part-of: opentelemetry
rules:
- apiGroups: [""]
  resources:
  - nodes
  - nodes/metrics
  - services
  - endpoints
  - pods
  verbs: ["get", "list", "watch"]
- apiGroups: [""]
  resources:
  - configmaps
  verbs: ["get"]
- apiGroups:
  - networking.k8s.io
  resources:
  - ingresses
  verbs: ["get", "list", "watch"]
- nonResourceURLs: ["/metrics"]
  verbs: ["get"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    app.kubernetes.io/component: opentelemetry-collector
    app.kubernetes.io/instance: blueprints.otel
    app.kubernetes.io/managed-by: manually
    app.kubernetes.io/name: otel-collector
    app.kubernetes.io/part-of: opentelemetry
  name: otel-collector-sa
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: otel-collector-sa
subjects:
- kind: ServiceAccount
  name: otel-collector-sa
  namespace: blueprints