apiVersion: monitoring.googleapis.com/v1
kind: PodMonitoring
metadata:
  name: blueprints-worker
  namespace: blueprints
spec:
  selector:
    matchLabels:
      app: blueprints-worker
  endpoints:
    - port: system
      interval: 5s